### ISSUE TITLE
Unable to cluster loci sequences

### ISSUE THREAD

**Issue by mpgriesh** [art-egorov/lovis4u#5]
It's unclear why clustering might fail given very similar input plasmid sequences which makes it very difficult to troubleshoot. Can you help me understand why this might happen?

lovis4u -gff plasmid_gffs/ -o plasmid_lovis/ -hl --reorient_loci
⦿ 85 loci were loaded from extended gff files folder
○ Running mmseqs for protein clustering...
⦿ 449 clusters for 3267 proteins were found with mmseqs
    mmseqs clustering results were saved to plasmid_lovis/mmseqs/mmseqs_clustering.tsv
lovis4uError 💔: Unable to cluster loci sequences.

**Comment by art-egorov** [comment]
Could you please provide the error message you get with added '-debug' parameter? I'll have a look tomorrow morning 

Best

**Comment by mpgriesh** [comment]
Thanks for the fast response and tool. Absolutely love it!

With a smaller example, it runs without error because the contig headers in the gffs were unique. Non-unique headers in the bigger set cause this error:

Traceback (most recent call last):
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 735, in cluster_sequences
    self.locus_annotation.loc[locus.seq_id, "group"] = locus.group
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 911, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 1944, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 2189, in _setitem_single_block
    value = self._align_series(indexer, Series(value))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/lib/python3.12/site-packages/pandas/core/indexing.py", line 2455, in _align_series
    raise ValueError("Incompatible indexer with Series")
ValueError: Incompatible indexer with Series

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/bin/lovis4u", line 26, in <module>
    loci.cluster_sequences(mmseqs_clustering_results, one_cluster= parameters.args["one_cluster"])
  File "/labs/asbhatt/mpgriesh/tools/miniconda3/lib/python3.12/site-packages/lovis4u/DataProcessing.py", line 762, in cluster_sequences
    raise lovis4u.Manager.lovis4uError("Unable to cluster loci sequences.") from error
lovis4u.Manager.lovis4uError: Unable to cluster loci sequences.

I expected the track names to be dependent on the file name rather than the contig headers. Updating the contig headers fixed that issue.

For a small test set of plasmids, I see homologous sequences are rotated relative to each other based on the assembler arbitrarily setting the coordinates. Is there a way within this tool to rotate tracks to best align homologous sequences? Sorry if I missed that...

**Comment by art-egorov** [comment]
Ah, yes, we expect that contig ids are unique. Sorry that the error message is confusing, it should be more clear and be displayed during the files processing. 

I'm now finishing a big update with a couple of new features and new visualisation styles. I will add an option to take contig id based on the file name. I'll drop another comment here about the option name and usage soon. 

About the rotation and alignment: yep, that the feature we plan to add in the next updates (within a couple of weeks), already in the to-do list :)

**Comment by art-egorov** [comment]
Hello again!

Now you can apply `--use-filename-as-id` parameter to use file name as contig id which can help to fix the problem :)

In addition, I added several new styles that are implemented through a set of config files for different A4 page layouts (suitable for preparing publication figure). Info about them is available at [user guide page](https://art-egorov.github.io/lovis4u/ExampleDrivenGuide/cmd_guide/) and examples are shown in the [gallery](https://art-egorov.github.io/lovis4u/Gallery/gallery/) 

Best,
Artyom

**Comment by mpgriesh** [comment]
Amazing, thank you Artyom!

Looking forward to the new features as they roll out :)

**Comment by Jiulong-Zhao** [comment]
Hi Artyom, 
Though the final error message for me is the same as mpgriesh's message, the error reasons are not the same.
My error message is as follows:
`
(base) zhaojiulongdeMacBook-Pro:lovis4u_plot zhaojiulong$ lovis4u -gff prokka_gffs/ --use-filename-as-id -debug
○ Reading gff files...
⦿ 91 loci were loaded from the gff files folder
○ Running mmseqs for protein clustering...
⦿ 104 clusters for 1056 proteins were found with mmseqs
	mmseqs clustering results were saved to lovis4u_2025_03_13-10_17/mmseqs/mmseqs_clustering.tsv
Traceback (most recent call last):
  File "/Users/zhaojiulong/.local/pipx/venvs/lovis4u/lib/python3.13/site-packages/lovis4u/DataProcessing.py", line 905, in cluster_sequences
    scipy.spatial.distance.squareform(symmetric_distance_matrix),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaojiulong/.local/pipx/venvs/lovis4u/lib/python3.13/site-packages/scipy/spatial/distance.py", line 2468, in squareform
    is_valid_dm(X, throw=True, name='X')
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaojiulong/.local/pipx/venvs/lovis4u/lib/python3.13/site-packages/scipy/spatial/distance.py", line 2573, in is_valid_dm
    raise ValueError(f"Distance matrix '{name}' must be symmetric.")
ValueError: Distance matrix 'X' must be symmetric.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaojiulong/.local/bin/lovis4u", line 31, in <module>
    loci.cluster_sequences(mmseqs_clustering_results, one_cluster=parameters.args["one_cluster"])
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaojiulong/.local/pipx/venvs/lovis4u/lib/python3.13/site-packages/lovis4u/DataProcessing.py", line 942, in cluster_sequences
    raise lovis4u.Manager.lovis4uError("Unable to cluster loci sequences.") from error
lovis4u.Manager.lovis4uError: Unable to cluster loci sequences.
(base) zhaojiulongdeMacBook-Pro:lovis4u_plot zhaojiulong$ lovis4u -gff prokka_gffs/ -o output/ -hl --reorient_loci --use-filename-as-id
○ Reading gff files...
⦿ 91 loci were loaded from the gff files folder
○ Running mmseqs for protein clustering...
⦿ 104 clusters for 1056 proteins were found with mmseqs
	mmseqs clustering results were saved to output/mmseqs/mmseqs_clustering.tsv
lovis4uError 💔: Unable to cluster loci sequences.

`
Besides, the mmseqs_clustering.tsv file seems right.

[mmseqs_clustering.txt](https://github.com/user-attachments/files/19220896/mmseqs_clustering.txt)

So, I wonder what happened in my work and how to solve it! 

Thank you so much!

Jiulong

**Comment by art-egorov** [comment]
Hi! 
It's strange, yes... i suspect it could be simply due to floating-point inconsistencies, now it should be fixed in version 0.1.4 that i released. At the same time, could you share (if it works now) the generated matrix _proteome_similarity_matrix.tsv_ so i will have a look that i haven't missed something else. 

Best

**Comment by Jiulong-Zhao** [comment]
Hi Artyom,
Thanks for your kindly reply!
Unfortunately, same error messages were still reported after I update the lovis4u version to 0.1.4.
The error messages are as follows:
`
(lovis4u) (python3) zhaojiulongdeMacBook-Pro:lovis4u_plot zhaojiulong$ lovis4u -gff prokka_gffs/ -debug
○ Reading gff files...
⦿ 91 loci were loaded from the gff files folder
○ Running mmseqs for protein clustering...
⦿ 104 clusters for 1056 proteins were found with mmseqs
	mmseqs clustering results were saved to lovis4u_2025_03_14-10_53/mmseqs/mmseqs_clustering.tsv
Traceback (most recent call last):
  File "/Users/zhaojiulong/software/lovis4u/lovis4u/lib/python3.13/site-packages/lovis4u/DataProcessing.py", line 908, in cluster_sequences
    scipy.spatial.distance.squareform(symmetric_distance_matrix),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaojiulong/software/lovis4u/lovis4u/lib/python3.13/site-packages/scipy/spatial/distance.py", line 2468, in squareform
    is_valid_dm(X, throw=True, name='X')
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaojiulong/software/lovis4u/lovis4u/lib/python3.13/site-packages/scipy/spatial/distance.py", line 2573, in is_valid_dm
    raise ValueError(f"Distance matrix '{name}' must be symmetric.")
ValueError: Distance matrix 'X' must be symmetric.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhaojiulong/software/lovis4u/lovis4u/bin/lovis4u", line 31, in <module>
    loci.cluster_sequences(mmseqs_clustering_results, one_cluster=parameters.args["one_cluster"])
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaojiulong/software/lovis4u/lovis4u/lib/python3.13/site-packages/lovis4u/DataProcessing.py", line 944, in cluster_sequences
    raise lovis4u.Manager.lovis4uError("Unable to cluster loci sequences.") from error
lovis4u.Manager.lovis4uError: Unable to cluster loci sequences.

`
I can send you my input files, and I will appreciate it if you can help me check these files.

Thanks!

Jiulong

[prokka_gffs.zip](https://github.com/user-attachments/files/19240386/prokka_gffs.zip)

**Comment by art-egorov** [comment]
Aha, I see, there are sequences in your set fully without any annotated features (coding or non-coding) which caused such issue - it couldn't normalise pairwise score correctly. 
I will release the update now (v 0.1.4.1) where it works fine. Files without any features will be skipped (anyway nothing to show). Thanks for your report!

Best

**Comment by Jiulong-Zhao** [comment]
Hi Artyom,
Thanks for your help!
This problem was totally solved!
I am really grateful that you released a new version for my issue!
Best!
Jiulong
